### PR TITLE
Remove/Don‘t install `openssh-blacklist` and `openssh-blacklist-extra`

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by drybjed** [comment]
Similar change is already in a pending PR: https://github.com/debops/ansible-sshd/pull/57/commits/7ab83138c5cfb8e7939777e8bc642ee8bcd7521b

Do you think that it's better to remove the package installation completely, or leave it for older OS releases?

**Comment by ypid** [comment]
I guess they won’t be needed anymore, including older releases. I guess we can just remove them completely.

**Comment by ypid** [comment]
Or lets just go with your PR :)

**Comment by ypid** [comment]
@drybjed Stretch is released now. Can you please merge this PR? Or cherry pick from #57 if you want.

**Comment by drybjed** [comment]
Agreed. I'll deal with merging my changes later.

**Pull request merged**
